// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type ResolveRequest struct {
	ShortCode string `path:"short_code" validate:"required,validShortUrl"`
}

type ResolveResponse struct {
	OriginalUrl string `json:"original_url"`
	ExpiresAt   string `json:"expires_at,optional"`
}

type ShortenRequest struct {
	LongUrl string `json:"long_url" validate:"required,max=2048,validLongUrl"`
}

type ShortenResponse struct {
	ShortCode string `json:"short_code"`
}
