// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type ShortenRequest struct {
	LongUrl string `json:"long_url" validate:"required,max=2048,validLongUrl"`
}

type ShortenResponse struct {
	ShortUrl string `json:"short_url"`
}

type ShowRequest struct {
	ShortUrl string `path:"short_url" validate:"required,validShortUrl"`
}

type ShowResponse struct {
	LongUrl string `json:"long_url"`
}
