// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type ConvertRequest struct {
	LongUrl string `json:"long_url" validate:"required,url,max=2000"`
}

type ConvertResponse struct {
	ShortUrl string `json:"short_url"`
}

type ShowRequest struct {
	ShortUrl string `json:"short_url" validate:"required,alphanumdash,min=4,max=20""`
}

type ShowResponse struct {
	LongUrl string `json:"long_url"`
}
