// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	shortener "github.com/AIXIA/shortener/internal/handler/shortener"
	"github.com/AIXIA/shortener/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/convert",
				Handler: shortener.ConvertHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/show",
				Handler: shortener.ShowHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
