// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shortUrlMapFieldNames          = builder.RawFieldNames(&ShortUrlMap{})
	shortUrlMapRows                = strings.Join(shortUrlMapFieldNames, ",")
	shortUrlMapRowsExpectAutoSet   = strings.Join(stringx.Remove(shortUrlMapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shortUrlMapRowsWithPlaceHolder = strings.Join(stringx.Remove(shortUrlMapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheShortUrlMapIdPrefix       = "cache:shortUrlMap:id:"
	cacheShortUrlMapMd5Prefix      = "cache:shortUrlMap:md5:"
	cacheShortUrlMapShortUrlPrefix = "cache:shortUrlMap:shortUrl:"
)

type (
	shortUrlMapModel interface {
		Insert(ctx context.Context, data *ShortUrlMap) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ShortUrlMap, error)
		FindOneByMd5(ctx context.Context, md5 string) (*ShortUrlMap, error)
		FindOneByShortUrl(ctx context.Context, shortUrl string) (*ShortUrlMap, error)
		Update(ctx context.Context, data *ShortUrlMap) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultShortUrlMapModel struct {
		sqlc.CachedConn
		table string
	}

	ShortUrlMap struct {
		Id         uint64       `db:"id"`          // 主键ID
		CreateAt   time.Time    `db:"create_at"`   // 创建时间
		CreateBy   string       `db:"create_by"`   // 创建者
		UpdateAt   time.Time    `db:"update_at"`   // 更新时间
		UpdateBy   string       `db:"update_by"`   // 更新者
		IsDel      uint64       `db:"is_del"`      // 是否删除：0正常1删除
		LongUrl    string       `db:"long_url"`    // 长链接
		Md5        string       `db:"md5"`         // 长链接MD5
		ShortUrl   string       `db:"short_url"`   // 短链接
		ExpireAt   sql.NullTime `db:"expire_at"`   // 过期时间
		ClickCount uint64       `db:"click_count"` // 点击次数
	}
)

func newShortUrlMapModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultShortUrlMapModel {
	return &defaultShortUrlMapModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`short_url_map`",
	}
}

func (m *defaultShortUrlMapModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	shortUrlMapIdKey := fmt.Sprintf("%s%v", cacheShortUrlMapIdPrefix, id)
	shortUrlMapMd5Key := fmt.Sprintf("%s%v", cacheShortUrlMapMd5Prefix, data.Md5)
	shortUrlMapShortUrlKey := fmt.Sprintf("%s%v", cacheShortUrlMapShortUrlPrefix, data.ShortUrl)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, shortUrlMapIdKey, shortUrlMapMd5Key, shortUrlMapShortUrlKey)
	return err
}

func (m *defaultShortUrlMapModel) FindOne(ctx context.Context, id uint64) (*ShortUrlMap, error) {
	shortUrlMapIdKey := fmt.Sprintf("%s%v", cacheShortUrlMapIdPrefix, id)
	var resp ShortUrlMap
	err := m.QueryRowCtx(ctx, &resp, shortUrlMapIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shortUrlMapRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShortUrlMapModel) FindOneByMd5(ctx context.Context, md5 string) (*ShortUrlMap, error) {
	shortUrlMapMd5Key := fmt.Sprintf("%s%v", cacheShortUrlMapMd5Prefix, md5)
	var resp ShortUrlMap
	err := m.QueryRowIndexCtx(ctx, &resp, shortUrlMapMd5Key, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `md5` = ? limit 1", shortUrlMapRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, md5); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShortUrlMapModel) FindOneByShortUrl(ctx context.Context, shortUrl string) (*ShortUrlMap, error) {
	shortUrlMapShortUrlKey := fmt.Sprintf("%s%v", cacheShortUrlMapShortUrlPrefix, shortUrl)
	var resp ShortUrlMap
	err := m.QueryRowIndexCtx(ctx, &resp, shortUrlMapShortUrlKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `short_url` = ? limit 1", shortUrlMapRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, shortUrl); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShortUrlMapModel) Insert(ctx context.Context, data *ShortUrlMap) (sql.Result, error) {
	shortUrlMapIdKey := fmt.Sprintf("%s%v", cacheShortUrlMapIdPrefix, data.Id)
	shortUrlMapMd5Key := fmt.Sprintf("%s%v", cacheShortUrlMapMd5Prefix, data.Md5)
	shortUrlMapShortUrlKey := fmt.Sprintf("%s%v", cacheShortUrlMapShortUrlPrefix, data.ShortUrl)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, shortUrlMapRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CreateBy, data.UpdateBy, data.IsDel, data.LongUrl, data.Md5, data.ShortUrl, data.ExpireAt, data.ClickCount)
	}, shortUrlMapIdKey, shortUrlMapMd5Key, shortUrlMapShortUrlKey)
	return ret, err
}

func (m *defaultShortUrlMapModel) Update(ctx context.Context, newData *ShortUrlMap) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	shortUrlMapIdKey := fmt.Sprintf("%s%v", cacheShortUrlMapIdPrefix, data.Id)
	shortUrlMapMd5Key := fmt.Sprintf("%s%v", cacheShortUrlMapMd5Prefix, data.Md5)
	shortUrlMapShortUrlKey := fmt.Sprintf("%s%v", cacheShortUrlMapShortUrlPrefix, data.ShortUrl)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shortUrlMapRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CreateBy, newData.UpdateBy, newData.IsDel, newData.LongUrl, newData.Md5, newData.ShortUrl, newData.ExpireAt, newData.ClickCount, newData.Id)
	}, shortUrlMapIdKey, shortUrlMapMd5Key, shortUrlMapShortUrlKey)
	return err
}

func (m *defaultShortUrlMapModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheShortUrlMapIdPrefix, primary)
}

func (m *defaultShortUrlMapModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shortUrlMapRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultShortUrlMapModel) tableName() string {
	return m.table
}
