CREATE TABLE IF NOT EXISTS `sequence`
(
    `id`        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `stub`      CHAR(1)         NOT NULL DEFAULT '0' COMMENT '填充位',
    `timestamp` TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_stub` (`stub`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8 COMMENT ='序号表';