# .github/workflows/sync-dev.yml
name: Sync dev with main
on:
  push:
    branches:
      - main  # main 分支有推送时触发

# 添加明确的权限配置
permissions:
  contents: write

jobs:
  sync-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4
        with:
          ref: dev  # 直接拉取 dev 分支

      - name: 合并 main 到 dev
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git fetch origin main
          
          # 尝试合并，如有冲突则中止并创建报告
          if ! git merge origin/main --no-edit; then
            echo "合并冲突发生，请手动解决冲突"
            git merge --abort
            exit 1
          fi
          
          git push origin dev