# .github/workflows/test.yml
name: Run Tests
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

# 添加明确的权限配置
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 设置 Go 环境
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Go 缓存
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: 运行测试
        run: go test -v -coverprofile=coverage.out ./...

      - name: 生成测试覆盖率报告
        run: go tool cover -func=coverage.out

